version: '3.4'

services:

  mutants:
    build:
      context: .
      dockerfile: ./services/mutants/Dockerfile
    volumes:
      - './services/mutants:/src'
    ports:
      - 3000:3000
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - MONGO_URI=mongodb://mutants_mongo_db:27017/mutants
      - MONGO_URI_TEST=mongodb://mutants_mongo_db:27017/mutants_test
    depends_on:
      - mutants_mongo_db

  mutants_mongo_db:
    image: mongo
    ports:
        - "27017:27017"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - mutants

  swagger:
    container_name: swagger
    build:
      context: .
      dockerfile: ./services/swagger/Dockerfile
    volumes:
      - './services/swagger/swagger.json:/usr/share/nginx/html/swagger.json'
    ports:
      - '8080:8080'
    environment:
      - URL=swagger.json
    depends_on:
      - mutants
